---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app-deployment
  labels:
    app: devops-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      initContainers:
        - name: devops-app-migration
          image: dev-ops-app_app
          command: ['/app/migrate.sh']
          imagePullPolicy: Never
      containers:
        - name: devops-app
          image: dev-ops-app_app
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
