version: "3.7"
services:
  app:
    build: ./
    restart: always
    
    environment:
      DJANGO_SETTINGS_MODULE: "settings"
    ports:
      - 8000:8000
    depends_on:
      - mysql


  mysql:
    image: mysql:5.7
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "app"

  migrations:
    build: ./
    restart: on-failure
    environment:
      DJANGO_SETTINGS_MODULE: "settings"
    command: "./migrate.sh"
    depends_on:
      - mysql
