# Generated by Django 3.0.2 on 2020-01-27 22:48

from django.db import migrations, models


def load_initial_data(apps, schema_editor):
    Product = apps.get_model('app', 'Product')

    products = [
        Product(
            name='Socks',
            description='Wonderfully froggy socks featuring Leap. Available in adult, children and infant sizes.',
            price=10.00
        ),
        Product(
            name='Hat',
            description='Shield your eyes from the sun with this Leap hat! One size fits all.',
            price=25.00
        ),
        Product(
            name='Onesie',
            description='Your baby will be the cutest anyone has ever seen when they wear this.',
            price=20.00
        ),
        Product(
            name='T-Shirt',
            description='A stylish t-shirt featuring Leap.',
            price=15.00
        )
    ]
    Product.objects.bulk_create(products)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.RunPython(
            load_initial_data,
            migrations.RunPython.noop
        )
    ]
